---
   - name: Restore Jenkins from S3 Backup
     hosts: localhost
     tasks:
       - name: Get latest backup from S3
         aws_s3:
           bucket: "{{ lookup('env', 'BACKUP_BUCKET') }}"
           object: "{{ item.key }}"
           dest: /tmp/jenkins_backup.tar.gz
           mode: get
         environment:
           AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
           AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
         loop: "{{ lookup('aws_s3', 'bucket={{ lookup(\"env\", \"BACKUP_BUCKET\") }} prefix=backups/').list | sort(attribute='last_modified', reverse=True) }}"
         register: s3_download
         when: item.key.endswith('.tar.gz')
         failed_when: s3_download.skipped is defined
         max_items: 1

       - block:
           - name: Stop Jenkins container
             docker_container:
               name: jenkins
               state: stopped
         ignore_errors: true

       - name: Remove existing Jenkins home
         file:
           path: /var/jenkins_home
           state: absent

       - name: Create Jenkins home directory
         file:
           path: /var/jenkins_home
           state: directory
           mode: '0755'

       - name: Extract backup
         unarchive:
           src: /tmp/jenkins_backup.tar.gz
           dest: /var/jenkins_home
           remote_src: yes

       - name: Start Jenkins container
         docker_container:
           name: jenkins
           image: jenkins/jenkins:lts
           state: started
           ports:
             - "8080:8080"
             - "50000:50000"
           volumes:
             - /var/jenkins_home:/var/jenkins_home